name: speedtest-yxcfip

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 8,20 * * *'  # 每12小时运行一次，可以根据需求调整

jobs:
  ip-speed-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests        

    - name: Run shell script
      env:
        AUTH_EMAIL: ${{ secrets.AUTH_EMAIL }}
        AUTH_KEY: ${{ secrets.AUTH_KEY }}
        ZONE_NAME: ${{ secrets.ZONE_NAME }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} 
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}         
      run: |
        chmod +x speed_AIO.sh
        sudo ./speed_AIO.sh hk                    #测速默认香港地区,默认端口443,修改域名为默认    hk.xxxx.com
        sudo ./speed_AIO.sh us                    #测速默认美国地区,默认端口443,修改域名为默认    us.xxxx.com
        sudo ./speed_AIO.sh kr                    #测速韩国地区,默认端口443,修改域名为默认        kr.xxxx.com
        sudo ./speed_AIO.sh jp                    #测速日本地区,默认端口443,修改域名为默认        jp.xxxx.com自定义端口8443,修改域名为默认     jp-8443.xxxx.com 6条IP记录
        sudo ./speed_AIO.sh sg                    #测速新加坡地区,默认端口443,修改域名为默认      sg.xxxx.com自定义端口2096,修改自定义域名为   sg-2096.google.com 8条IP记录
        
    - uses: stefanzweifel/git-auto-commit-action@v5


   
        
